name: "[via MDN pages only // ru]"
description: Issue filed via "Report a problem with this content on GitHub" link on MDN pages.
labels: ["l10n-ru", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Прежде чем начать

        **Готовы внести правки самостоятельно?** Веб-документацию MDN может редактировать каждый!
        ↩ Для этого вернитесь обратно в статью и кликните на ссылку _Edit on GitHub_.

        **Проблема с браузерной совместимостью?**
        ↩ Пожалуйста, вернитесь обратно в статью и кликните на ссылку _Report problems with this compatibility data on GitHub_.

        **Есть замечания по работе браузера?**
        🙋 Багтрекеры основных браузеров: [Firefox](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla), [Chrome](https://support.google.com/chrome/answer/95315?hl=en-GB&ref_topic=7439544), [Safari](https://www.apple.com/feedback/safari.html). Если вы используете другой браузер, пожалуйста, найдите его багтрекер самостоятельно.

        ---
  - type: input
    id: mdn-url
    attributes:
      label: MDN URL
      description: Заполнится само, пожалуйста, не правьте.
    validations:
      required: true
  - type: input
    id: section
    attributes:
      label: О какой части статьи или абзаце идёт речь?
  - type: textarea
    id: problem
    attributes:
      label: Что не так?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Как должно быть?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Есть ли у вас какие-либо подтверждающие ссылки?
      description: Это поможет нам быстрее разобраться в проблеме и всё исправить.
  - type: textarea
    id: more-info
    attributes:
      label: Хотите добавить что-то ещё?
      description: Например, инструкция, как воспроизвести ошибку, или скриншоты, записи экрана, пример кода...
  - type: markdown
    attributes:
      value: |
        ---
        Готово! Остальные поля заполнятся сами. Пожалуйста, нажмите **Submit new issue**.
  - type: textarea
    id: metadata
    attributes:
      label: MDN metadata
      description: Заполнится само, пожалуйста, не правьте.
