name: Sync Translated Content

on:
  workflow_dispatch:
    inputs:
      notes:
        description: "Notes"
        required: false
        default: ""
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 */24 * * *"

jobs:
  build:
    if: github.repository == 'mdn/translated-content'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        lang:
          - es
          - fr
          - ja
          - ko
          - pt-br
          - ru
          - zh-cn
          - zh-tw

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: mdn/content
          path: mdn/content

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: mdn/content/yarn.lock

      - name: Install all yarn packages
        working-directory: ${{ github.workspace }}/mdn/content
        run: yarn --frozen-lockfile

      - name: Sync translated content
        env:
          CONTENT_ROOT: ${{ github.workspace }}/mdn/content/files
          CONTENT_TRANSLATED_ROOT: ${{ github.workspace }}/files
        working-directory: ${{ github.workspace }}/mdn/content
        run: yarn content sync-translated-content ${{ matrix.lang }}

      - name: Generate relative commit message
        run: |
          git add files/${{ matrix.lang }}
          FILE_NAMES=$(git diff --name-only --cached | egrep -i "^files/${{ matrix.lang }}/.*\.md$")
          # get the reflecting commit of en-US
          cd mdn/content
          # generate a string for each line in '<file name> <commit hash>'
          EN_US_COMMIT=$(echo "${FILE_NAMES}" | sed '0,/${{ matrix.lang }}/s//en-us/' | \
            xargs -L1 git log -1 --format="%H")
          COMMIT_MESSAGE=$(paste -d ' mdn/content@' <(echo "${FILE_NAMES}") <(echo "${EN_US_COMMIT}"))
          # add '- ' prefix to each line
          COMMIT_MESSAGE=$(echo "${COMMIT_MESSAGE}" | sed 's/^/- /')
          COMMENT="Reflected commit in en-US:"$'\n'"${COMMIT_MESSAGE}"

          # set the environment variable for the next step
          DELIMITER="$(openssl rand -hex 16)"
          echo "COMMENT<<${DELIMITER}" >> $GITHUB_ENV
          echo "${COMMENT}" >> $GITHUB_ENV
          echo "${DELIMITER}" >> $GITHUB_ENV

      - name: Create PR with sync for ${{ matrix.lang }}
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "${{ matrix.lang }}: sync translated content"
          branch: content-sync-${{ matrix.lang }}
          title: "[${{ matrix.lang }}] sync translated content"
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          body: |
            Yari generated sync.

            ${{ env.COMMENT }}
          token: ${{ secrets.AUTOMERGE_TOKEN }}
